name: "Caching Example"

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - '1.x'
    - 'master'

jobs:
  caching-example:
    name: Caching
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('etc/example-environment.yml') }}
      - uses: goanpeca/setup-miniconda@enh/poststep
        with:
          activate-environment: anaconda-client-env
          python-version: 3.8
          channel-priority: strict
          environment-file: etc/example-environment.yml
          use-only-tar-bz2: true
