name: "Example 3: Other options"

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - '1.x'
    - 'master'

jobs:
  example-3:
    name: Ex3 Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@1.x
        with:
          activate-environment: anaconda-client-env
          environment-file: etc/example-environment.yml
          python-version: 3.5
          condarc-file: etc/example-condarc.yml
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
