name: "Example 4: Channels"

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - '1.x'
    - 'master'

jobs:
  example-4:
    name: Ex4 Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@master
        with:
          activate-environment: foo
          python-version: 3.6
          channels: conda-forge,spyder-ide
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
